name: generate snake animation
on:
  #cronで自動実行の設定ができる
  schedule:
    - cron: "0 1 * * *"
  #手動でjobを実行できる
  workflow_dispatch:
  #main branchにpushさせるようにする
  push:
    branches:
      - main

jobs:
  update-repository:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./dist/snake/github-contribution-grid-snake.svg
            ./dist/snake/github-contribution-grid-snake-dark.svg?palette=github-dark
